1.Find out whether a matrix is a diagonal matrix.  (First check whether the matrix is a square matrix and then check whether the non diagonal elements are zeroes).

2.Find out whether a matrix is a skew-symmetric matrix.  (First check whether the matrix is a square matrix and then check whether a_ij = - a_ji)

3.Find an inverse of a matrix by finding its determinant, minor, cofactor and adjugate.

In [1]:
import numpy as np

In [2]:
def issquare(r,c):
    if r == c:
        return True
    else: False

In [3]:
def isdiagonal(m,r,c):
    if(issquare(r,c)):
        for i in range(r):
            for j in range(c):
                if i != j and m[i][j] != 0:
                    
                    return False
        return True
    else: print('Not a square Matrix')


In [4]:
m = np.array([[3, 0, 0],[0, 4, 0],[0, 0, 10]])
r,c = m.shape
if(isdiagonal(m,r,c)):
    print('Matrix is a diagonal matrix')
else: 
    print('Matrix is not a diagonal matrix')


Matrix is a diagonal matrix


In [5]:
def isskew_symmetric(m,r,c):
    if(issquare(r,c)):
        mt = m.transpose()
        print('matrix:\n',m)
        print('matrix transpose:\n',mt)
        print('(-1)*matrix:\n',(-1)*m)
        if(mt == -m).all():
            return True
        else:
            return False
    else: print('Not a square Matrix')

In [6]:
m = np.array([[0, 5, -4],[-5, 0, 1],[4, -1, 0]])
r,c = m.shape
if(isskew_symmetric(m,r,c)):
    print('Matrix is a skew-symmetric matrix')
else: 
    print('Matrix is not a skew-symmetric matrix')


matrix:
 [[ 0  5 -4]
 [-5  0  1]
 [ 4 -1  0]]
matrix transpose:
 [[ 0 -5  4]
 [ 5  0 -1]
 [-4  1  0]]
(-1)*matrix:
 [[ 0 -5  4]
 [ 5  0 -1]
 [-4  1  0]]
Matrix is a skew-symmetric matrix


In [7]:
def det(m):
    (nr,nc) = m.shape
    if issquare(nr,nc) == False:
        print('Not a square Matrix')
        return m
    #end if

    if nr == 1 and nc == 1:
        return m[0,0]
    else:
        D = 0
        for r in range(0,1):
            for c in range(0,nc):
                reducedmat = m.copy()
                reducedmat = np.delete(reducedmat,r,0)
                reducedmat = np.delete(reducedmat,c,1)
                D = D + (((-1)**((r+1)+(c+1))) * m[r,c] * det(reducedmat))
    #end if
    return D

In [8]:
C = np.array([[2,-2,2],
              [2,3,-3],
              [0,10,0]])
print(C)
print('det(C) = %f' %(np.linalg.det(C)))

[[ 2 -2  2]
 [ 2  3 -3]
 [ 0 10  0]]
det(C) = 100.000000


In [9]:
C = np.array([[2,-2,2,-1],
              [2,3,-3,1],
              [0,10,0,5],
              [-2,4,1,3]])
print(C)
print('det(C) = %f' %(np.linalg.det(C)))

[[ 2 -2  2 -1]
 [ 2  3 -3  1]
 [ 0 10  0  5]
 [-2  4  1  3]]
det(C) = 70.000000


In [10]:
print('calculat det = %f' %(det(C)))

calculat det = 70.000000


In [11]:
def transpose(matrix):
    return [[row[i] for row in matrix] for i in range(len(matrix[0]))]

In [12]:
def Minor(arr,i,j):
    c = arr[:]
    c_r = np.delete(c, (i),axis=0) # deletes i-th row
    c_c = np.delete(c_r, (j),axis=1) #deletes j-th column
    return c_c

In [13]:
def inverse(m):
    determinant = det(m)

    #find matrix of cofactors
    cofactors = []
    for r in range(len(m)):
        cofactorRow = []
        for c in range(len(m)):
            minor = Minor(m,r,c)
            cofactorRow.append(((-1)**(r+c)) * det(minor))
        cofactors.append(cofactorRow)
    cofactors = transpose(cofactors)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = round(cofactors[r][c]/determinant,8)
    return cofactors

In [14]:
I = np.array([[2,3,-4,-1],
              [4,2,-3,11],
              [3,-9,2,-5],
              [7,10,-8,1]])
print(I)
print('Inverse of I matrix by code = ')
print(inverse(I))
print('Inverse of I matrix by numpy = ')
print(np.linalg.inv(I))

[[ 2  3 -4 -1]
 [ 4  2 -3 11]
 [ 3 -9  2 -5]
 [ 7 10 -8  1]]
Inverse of I matrix by code = 
[[-0.33769776, -0.00109111, 0.10420076, 0.19530824], [-0.2487725, -0.06219313, -0.06055646, 0.13256956], [-0.6061102, -0.06819422, 0.01254774, 0.20676487], [0.00272777, 0.08401528, -0.02345881, -0.03873432]]
Inverse of I matrix by numpy = 
[[-0.33769776 -0.00109111  0.10420076  0.19530824]
 [-0.2487725  -0.06219313 -0.06055646  0.13256956]
 [-0.6061102  -0.06819422  0.01254774  0.20676487]
 [ 0.00272777  0.08401528 -0.02345881 -0.03873432]]
