In [56]:
# 1.Modify the Gauss's Elimination code provided in the lecture 7 to include part 1 of the row echelon procedure (to normalize the first non-zero coefficient to 1).
import numpy as np

In [57]:
def fwd_gauss_recursive(Ab):
    # check the size of the augmented matrix
    [nr,nc] = Ab.shape
    print('nr = ', nr)
    if nc != nr + 1:
        print('Error: inappropriate matrix size')
    else:
        if nr == 1:
            GEM = Ab
        else:
            for r in range(0,nr):
                # normalizing row r
                k = Ab[r,r]
                Ab[r,:] = (1/k) * Ab[r,:]
            # perform GaussElimination from the 2nd row onwards
                for i in range(r+1,nr):
                    row_factor = Ab[i,0]/Ab[0,0]
                    Ab[i,:] = Ab[i,:] - row_factor * Ab[0,:]
                # end for each row r
            GEM = Ab
            # remove first row and first column for the next recursion
            GEM_next_input = GEM[1:nr,1:nc]
            GEM_next_output = fwd_gauss_recursive(GEM_next_input)
        # end if (nr==1)
    # end if (nc != nr + 1)
    print(GEM)
    return GEM

In [58]:
Ab = np.array([(4.0,-2.0,1.0,8.0),
               (1.0,1.0,1.0,-13.0),
               (9.0,3.0,1.0,3.0)])


In [59]:
print('Ab = ')
print(Ab)


Ab = 
[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [60]:
GAb = fwd_gauss_recursive(Ab)
print('GAb = ')
print(GAb)

nr =  3
nr =  2
nr =  1
[[  1. -12.]]
[[  1.    0.5 -10. ]
 [  0.    1.  -12. ]]
[[  1.    -0.5    0.25   2.  ]
 [  0.     1.     0.5  -10.  ]
 [ -0.     0.     1.   -12.  ]]
GAb = 
[[  1.    -0.5    0.25   2.  ]
 [  0.     1.     0.5  -10.  ]
 [ -0.     0.     1.   -12.  ]]
