In [53]:
# 2. Modify the code for Gauss-Jordan Elimination such that you can find the inverse of a matrix A.  A = [[3,0,2],[2,0,-2],[0,1,1]].
import numpy as np
import sys

In [54]:
def issquare(r,c):
    if r == c:
        return True
    else: False

In [55]:
# Augmenting Identity Matrix of Order n
def identityMatrix(m):
    [nr,nc] = m.shape
    idm = np.zeros((nr,2*nr))
    if issquare(nr,nc):    
        for r in range(nr):        
            for c in range(nc):
                idm[r][c] = m[r][c]
                if r == c:
                    idm[r][c+nr] = 1
        return idm
    else: return idm

# Applying Guass Jordan Elimination
def guassJordan(m):
    [nr,nc] = m.shape
    for i in range(nr):
        if m[i][i] == 0.0:
            sys.exit('Divide by zero detected!')
        for j in range(nr):
            if i != j:
                ratio = m[j][i]/m[i][i]
                for k in range(2*nr):
                    m[j][k] = m[j][k] - ratio * m[i][k]

    # Row operation to make principal diagonal element to 1
    for i in range(nr):
        divisor = m[i][i]
        for j in range(2*nr):
            m[i][j] = m[i][j]/divisor
    return m

In [56]:
A = np.array([[1,1,3],[1,3,-3],[-2,-4,-4]])
print(A)

[[ 1  1  3]
 [ 1  3 -3]
 [-2 -4 -4]]


In [57]:
ident = identityMatrix(A)
# print(ident)
inv = guassJordan(ident)
print('The Gauss-Jordan Elimination is:')
print(inv)
print('The inverse is:')
print(np.linalg.inv(A))

The Gauss-Jordan Elimination is:
[[ 1.    0.    0.    3.    1.    1.5 ]
 [ 0.    1.    0.   -1.25 -0.25 -0.75]
 [-0.   -0.    1.   -0.25 -0.25 -0.25]]
The inverse is:
[[ 3.    1.    1.5 ]
 [-1.25 -0.25 -0.75]
 [-0.25 -0.25 -0.25]]
